---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
  namespace: ahmed-tawazun
  labels:
    name: ahmed
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-069e06693c89310cc
    fsType: ext4
