---
apiVersion: v1
kind: Service
metadata:
  name: tawazun-svc
  namespace: ahmed-tawazun
  labels: 
    name: ahmed
spec:
  selector:
    app: deployapp
  ports:
    - port: 80 
      targetPort: 8080
  type: LoadBalancer  
